AESD_CHAR_DRIVER_VERSION = 9986dee501de896e80223a59b212fd93027a9f64
AESD_CHAR_DRIVER_SITE = https://github.com/cu-ecen-aeld/assignments-3-and-later-Jaju8756.git
AESD_CHAR_DRIVER_SITE_METHOD = git
AESD_CHAR_DRIVER_GIT_SUBMODULES = YES

AESD_CHAR_DRIVER_LICENSE = GPL-2.0
AESD_CHAR_DRIVER_LICENSE_FILES = LICENSE

AESD_CHAR_DRIVER_MODULE_SUBDIRS = aesd-char-driver

$(eval $(kernel-module))
$(eval $(generic-package))
